### ISSUE TITLE
Create Site Nav components

### ISSUE THREAD

**Issue by miherb** [tjikko-studio/components#10]
1- Review the previous components for **Site Nav** that are already developed
2- Create or add what it is missing to generate the generic components. Make sure the components are reusable and that all the texts and images they show are dynamic. Use sensible placeholders for all texts and images if necessary. It should use the components already developed in [Nav items](https://github.com/tjikko-studio/components/issues/9) elevated.
3- Add to Storybook.

**Regular navigation**

![Screen Shot 2021-07-05 at 10 40 21 AM](https://user-images.githubusercontent.com/9423771/124488069-6cbe6680-dd7d-11eb-885d-281546a0cc81.png)

It's [here](https://www.figma.com/file/M9qxBl0DRvZ0dh2o1YChh9/SmartPixel-Design-System?node-id=1299%3A66710) in the design file.

**To-Do**
- [x] Black Scheme - Regular nav
- [x] Transparent White - Regular nav
- [x] Black Scheme - Below 1024px nav
- [x] Transparent White - Below 1024px nav
- [x] Black Scheme - Below 475px nav
- [x] Transparent White - Below 475px nav

**Mobile navigation**

<img width="182" alt="Screen Shot 2021-07-03 at 5 55 15 PM" src="https://user-images.githubusercontent.com/9423771/124367722-df1d3280-dc27-11eb-8e12-b736a79c8c24.png">

**To-Do**
- [x] Nav open
