### ISSUE TITLE
Create Blocks Logo Pizza components

### ISSUE THREAD

**Issue by miherb** [tjikko-studio/components#13]
1- Review the previous components for **Blocks / Logo Pizza** that are already developed (if any)
2- Create or add what it is missing to generate the generic components. Make sure the components are reusable and that all the texts and images they show are dynamic. Use sensible placeholders for all texts and images if necessary. 
3- Add to Storybook.

<img width="670" alt="Screen Shot 2021-07-11 at 11 17 55 AM" src="https://user-images.githubusercontent.com/9423771/125200559-b0abe280-e239-11eb-9317-e69945a97b76.png">

**To-Do**
An infinite automatic carroussel:

- [ ] Default - Above 1024px
- [ ] Default - Above 768px
- [ ] Default - Below 640px
- [ ] Compact - Above 1024px
- [ ] Compact - Above 768px
- [ ] Compact - Below 640px
