### ISSUE TITLE
Create Big Headers components

### ISSUE THREAD

**Issue by miherb** [tjikko-studio/components#20]
1- Review the previous components for **Big Headers** that are already developed (if any)
2- Create or add what it is missing to generate the generic components. Make sure the components are reusable and that all the texts and images they show are dynamic. Use sensible placeholders for all texts and images if necessary. It should use the components already developed in [Header Text default](https://github.com/tjikko-studio/components/issues/19).
3- Add to Storybook.

<img width="808" alt="Screen Shot 2021-07-03 at 8 03 06 PM" src="https://user-images.githubusercontent.com/9423771/124369409-b4d47080-dc39-11eb-880d-988771aebda7.png">

**To-Do**
- [x] Default - Above 1024px
- [x] Default - Below 1024px
- [x] Default - Below 475px
