### ISSUE TITLE
Create Regular Headers components

### ISSUE THREAD

**Issue by miherb** [tjikko-studio/components#24]
1- Create **Regular Headers** generic components. Make sure the components are reusable and that all the texts and images they show are dynamic. Use sensible placeholders for all texts and images if necessary. It should use the components already developed in [Header Text default](https://github.com/tjikko-studio/components/issues/19).
2- Add to Storybook.

![Screen Shot 2021-07-04 at 9 45 13 AM](https://user-images.githubusercontent.com/9423771/124387411-8f347f00-dcac-11eb-9ec0-e1212836add5.png)

**To-Do**
- [ ] Default - Above 1024px
- [ ] Default - Below 1024px
- [ ] Default - Below 475px
