### ISSUE TITLE
Create Regular Header components

### ISSUE THREAD

**Issue by miherb** [tjikko-studio/components#44]
1- Generate the generic components for Regular Headers. Make sure the components are reusable and that all the texts and images they show are dynamic. Use sensible placeholders for all texts and images if necessary. It should use the components already developed in [Header Text default](https://github.com/tjikko-studio/components/issues/19). It should be really similar to Big Header.
2- Add to Storybook.

<img width="834" alt="Screen Shot 2021-07-12 at 5 37 04 PM" src="https://user-images.githubusercontent.com/9423771/125359102-cef80800-e337-11eb-8d99-bdb4fc1cbb30.png">

**To-Do**
- [] Default - Above 1024px
- [] Default - Below 1024px
- [] Default - Below 475px
